#!/usr/bin/env bash
# Install load balancer
sudo apt -y update

sudo apt -y install software-properties-common
sudo apt-add-repository -y ppa:vbernat/haproxy-1.8

sudo apt -y update
sudo apt -y install haproxy=1.8\*

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy

sudo echo "listen 2851-lb-01" >> /etc/haproxy/haproxy.cfg
sudo echo "	bind 0:80" >> /etc/haproxy/haproxy.cfg
sudo echo "	mode http" >> /etc/haproxy/haproxy.cfg
sudo echo "	stats enable" >> /etc/haproxy/haproxy.cfg
sudo echo "	balance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo "	option httpclose" >> /etc/haproxy/haproxy.cfg
sudo echo "	option forwardfor" >> /etc/haproxy/haproxy.cfg                                                                                  
sudo echo "server 2851-web-01 3.89.247.193 check port 80" >> /etc/haproxy/haproxy.cfg                                                        
sudo echo "server 2851-web-02 54.227.58.38 check port 80" >> /etc/haproxy/haproxy.cfg                                                      

sudo service haproxy restart
