#!/usr/bin/env bash
# Install load balancer
sudo apt-get -y update && sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 349-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 4976-web-01 3.89.247.193 check\n\tserver 4976-web-02 54.227.58.38 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
