#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/mimolmon permanent;" /etc/nginx/sites-enabled/default
service nginx start
